### PR TITLE
Improve ValueTransformer type detection

### PR DESCRIPTION
**Pull request by twz123**
The current `ValueTransformer` type detection implementation in `ValueTransformerUtils` works only for simple use cases.

The type detection fails for the following class structure:

``` java

/**
 * A custom value that shall be transformed using a {@link ValueTransformer}.
 */
public class CustomValue {
    // just a dummy type
}

/**
 * A custom bound that shall be transformed using a {@link ValueTransformer}.
 */
public class CustomBound {
    // just a dummy type
}

/**
 * An example for an abstract parameterized transformer that does
 * &quot;something&quot; and then delegates to a subclass's method.
 */
public abstract class AbstractParameterizedTransformer<Value, Bound> extends ValueTransformer<Value, Bound> {

    @Override
    public Bound unmarshalFromDb(final String value) {
        return delegatedUnmarshalling(value);
    }

    @Override
    public Value marshalToDb(final Bound bound) {
        return delegatedMarshalling(bound);
    }

    // actual unmarshalling performed by subclasses that operate on a preprocessed value
    protected abstract Bound delegatedUnmarshalling(String preprocessed);

    // actual marshalling performed by subclasses that operate on a preprocessed value
    protected abstract Value delegatedMarshalling(Bound preprocessed);
}

/**
 * An example for a concrete transformer that uses an abstract parameterized
 * transformer as a superclass.
 */
public class ConcreteTransformer extends AbstractParameterizedTransformer<CustomValue, CustomBound> {
    @Override
    protected CustomBound delegatedUnmarshalling(final String preprocessed) {
        return null; // doesn't do anything meaningful, just an example
    }

    @Override
    protected CustomValue delegatedMarshalling(final CustomBound preprocessed) {
        return null; // doesn't do anything meaningful, just an example
    }
}
```

This PR uses Guava's `TypeToken` to resolve the generic type parameters of `ValueTransformer` against the concrete subclasses, which should work for all possible class structures.

### CODE REVIEW

**Comment by twz123** [comment]
@hjacobs  Any chance getting this merged? I just encountered this shortcoming again and totally forgot about it.

**Comment by valgog** [comment]
@twz123 I would love to merge this.

@vadeg can you have a brief look on this?

**Comment by vadeg** [comment]
@valgog could you please update this PR from master? It was built one year ago and I would like to make sure it works. Unfortunately, I can not update it with master neither re-trigger build in Travis. Maybe permissions problems.

**Comment by twz123** [comment]
Two years later and still: "This merge commit was added into this branch cleanly." ;)

**Comment by vadeg** [comment]
@twz123 could you please update `guava` to `22.0` and `mockito-core` to `2.8.47`?

**Comment by twz123** [comment]
@vadeg done

**Comment by vadeg** [comment]
@twz123 Thanks!

**Pull request merged**
