### PR TITLE
GH-37 Make stored procedure immutable

### LINKED ISSUE #37: StoredProcedure is not thread safe but used in multithreaded context
`StoredProcedure` is wrapped in `Call` (which implements `Callable`) and passed to thread pool. 
If two concurrent threads try to execute `Callable` one of them could observe uninitialized types in `StoredProcedure.getTypes()` 

See `StoredProcedure.executeInParallel()`
https://github.com/zalando-incubator/java-sproc-wrapper/blob/master/src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java#L590

and `StoredProcedure.getTypes()` 
https://github.com/zalando-incubator/java-sproc-wrapper/blob/master/src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java#L218

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Fixes #37

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
This is extension of #39

**Comment by jhorstmann** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
Summoning @valgog @Jan-M @jbellmann for peer review

**Comment by valgog** [comment]
Oh, I have missed this PR, sorry @AlexanderYastrebov .

I suppose it is still a valid one, is it?

**Comment by AlexanderYastrebov** [comment]
@valgog Probably, since last change in master is dated  Aug 25, 2016

**Comment by valgog** [comment]
@AlexanderYastrebov I looked through the changes briefly and they look ok. I do not really know how to most efficiently test these multithreading and concurrency related changes.

👍 from my side for the merger.

@Jan-M can you have a look on the PR and spend some time on that?

**Comment by Jan-M** [comment]
:+1: from me without any deeper investigation as you two think it is ok.

I am not allowed to merge - don't know who owns this now.

**Comment by valgog** [comment]
@Jan-M it seems that I can still merge it :D

**Pull request merged**
